import { Feedback } from "./schema";

// Helper function to create dates in the past
function daysAgo(days: number): Date {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date;
}

function hoursAgo(hours: number): Date {
  const date = new Date();
  date.setHours(date.getHours() - hours);
  return date;
}

export const mockFeedbacks: Feedback[] = [
  {
    id: "9b3f11bd-07ad-4055-865d-56b05368fec1",
    from: "thuillartarmand@gmail.com",
    impact: "critical",
    subject: "App freezes and UI issues",
    text: "Hey, real quick—your app's cool but driving me nuts.  \n\n• It freezes every time I switch back to it (hello, lost notes 😡)  \n• That tiny 'Send Feedback' link is impossible to tap—seriously?  \n• Dark mode looks great but the contrast is awful on text  \n\nPlease sort these bugs, make buttons bigger, and fix the freeze already. Thx.",
    summary:
      "Armand is experiencing app freezes when switching back, finds the feedback link too tiny to tap, and mentions dark mode contrast problems.",
    tags: ["bug", "ui", "performance", "ux"],
    metadata: null,
    createdAt: hoursAgo(2),
    updatedAt: hoursAgo(2),
  },

  {
    id: "7c4e22ce-18be-5166-976e-67c16479gfd2",
    from: "sarah.designer@example.com",
    impact: "major",
    subject: "Design inconsistencies in mobile view",
    text: "I've noticed several design inconsistencies in the mobile view that affect the overall user experience. The spacing is inconsistent, and some elements are misaligned.",
    summary:
      "Sarah noticed several design inconsistencies in the mobile view that affect the overall user experience.",
    tags: ["ui", "ux", "enhancement"],
    metadata: null,
    createdAt: hoursAgo(8),
    updatedAt: hoursAgo(8),
  },
  {
    id: "5d3f33df-29cf-6277-087f-78d27580hge3",
    from: "john.developer@example.com",
    impact: "minor",
    subject: "Small typo in error message",
    text: "There's a typo in the error message when uploading large files. It says 'to large' instead of 'too large'.",
    summary:
      "John found a typo in the error message when uploading large files.",
    tags: ["bug", "ui"],
    metadata: null,
    createdAt: hoursAgo(16),
    updatedAt: hoursAgo(16),
  },
  {
    id: "3e4g44eg-40dg-7388-198g-89e38691ihf4",
    from: "emma.user@example.com",
    impact: "critical",
    subject: "Data loss after app crash",
    text: "I lost all my work after the app crashed unexpectedly. There was no auto-save triggered, and I had to start over from scratch.",
    summary:
      "Emma lost her work after the app crashed unexpectedly. No auto-save was triggered.",
    tags: ["bug", "performance"],
    metadata: null,
    createdAt: hoursAgo(22),
    updatedAt: hoursAgo(22),
  },
  {
    id: "1f5h55fh-51eh-8499-209h-90f49702jig5",
    from: "mike.tester@example.com",
    impact: "major",
    subject: "Performance issues with large datasets",
    text: "The app becomes very slow when working with datasets containing more than 1000 rows. Scrolling and filtering operations take several seconds to complete.",
    summary:
      "Mike reports significant slowdown when working with datasets containing more than 1000 rows.",
    tags: ["performance", "enhancement"],
    metadata: null,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: "9g6i66gi-62fi-9500-310i-01g50813kjh6",
    from: "lisa.ux@example.com",
    impact: "minor",
    subject: "Accessibility improvements needed",
    text: "We should add more keyboard shortcuts and improve screen reader compatibility. Currently, some features are only accessible via mouse.",
    summary:
      "Lisa suggests adding more keyboard shortcuts and improving screen reader compatibility.",
    tags: ["ux", "enhancement"],
    metadata: null,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: "7h7j77hj-73gj-0611-421j-12h61924lki7",
    from: "alex.dev@example.com",
    impact: "critical",
    subject: "Security vulnerability in authentication",
    text: "I discovered a potential security issue in the authentication flow. The session token is not being properly invalidated after logout.",
    summary:
      "Alex discovered a potential security issue in the authentication flow that needs immediate attention.",
    tags: ["security", "bug"],
    metadata: null,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: "5i8k88ik-84hk-1722-532k-23i72035mlj8",
    from: "rachel.qa@example.com",
    impact: "major",
    subject: "Inconsistent behavior across browsers",
    text: "The app behaves differently in Firefox compared to Chrome and Safari. Some features work in one browser but not in others.",
    summary:
      "Rachel found that the app behaves differently in Firefox compared to Chrome and Safari.",
    tags: ["bug", "ui", "ux"],
    metadata: null,
    createdAt: daysAgo(6),
    updatedAt: daysAgo(6),
  },
  {
    id: "3j9l99jl-95il-2833-643l-34j83146nmk9",
    from: "tom.user@example.com",
    impact: "minor",
    subject: "Feature request: Dark mode",
    text: "I would love to see a dark mode option added to the application. The current light theme is too bright for night-time use.",
    summary:
      "Tom would like to see a dark mode option added to the application.",
    tags: ["feature_request", "ui", "ux"],
    metadata: null,
    createdAt: daysAgo(8),
    updatedAt: daysAgo(8),
  },
  {
    id: "1k0m00km-06jm-3944-754m-45k94257onl0",
    from: "sophie.design@example.com",
    impact: "major",
    subject: "Mobile responsiveness issues",
    text: "The layout breaks on certain mobile devices and screen sizes. Elements overlap and become unusable on smaller screens.",
    summary:
      "Sophie reports that the layout breaks on certain mobile devices and screen sizes.",
    tags: ["ui", "ux", "enhancement"],
    metadata: null,
    createdAt: daysAgo(17),
    updatedAt: daysAgo(17),
  },
  {
    id: "2l1n11ln-17kn-4055-865n-56l05368pol1",
    from: "david.analyst@example.com",
    impact: "critical",
    subject: "API rate limiting issues",
    text: "The API rate limiting is too aggressive and causing legitimate requests to fail. We need to adjust the thresholds.",
    summary:
      "David reports that the API rate limiting is too aggressive and causing legitimate requests to fail.",
    tags: ["api", "performance"],
    metadata: null,
    createdAt: daysAgo(25),
    updatedAt: daysAgo(25),
  },
  {
    id: "4m2o22mo-28lo-5166-976o-67m16479qpm2",
    from: "anna.support@example.com",
    impact: "major",
    subject: "Customer support integration needed",
    text: "We should integrate with popular customer support platforms for better ticket management and tracking.",
    summary:
      "Anna suggests integrating with popular customer support platforms for better ticket management.",
    tags: ["enhancement", "api"],
    metadata: null,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: "6n3p33np-39mp-6277-087p-78n27580rqn3",
    from: "peter.legal@example.com",
    impact: "minor",
    subject: "GDPR compliance updates",
    text: "We need to update our data handling practices to ensure full GDPR compliance, especially for EU users.",
    summary:
      "Peter requests updates to ensure full GDPR compliance in data handling.",
    tags: ["legal", "enhancement"],
    metadata: null,
    createdAt: daysAgo(35),
    updatedAt: daysAgo(35),
  },
  {
    id: "8o4q44oq-40nq-7388-198q-89o38691sqo4",
    from: "maria.dev@example.com",
    impact: "critical",
    subject: "Database connection pool exhaustion",
    text: "The database connection pool is being exhausted under heavy load, causing timeouts and failed requests.",
    summary:
      "Maria reports that the database connection pool is being exhausted under heavy load.",
    tags: ["performance", "bug"],
    metadata: null,
    createdAt: daysAgo(40),
    updatedAt: daysAgo(40),
  },
  {
    id: "0p5r55pr-51or-8499-209r-90p49702trp5",
    from: "james.architect@example.com",
    impact: "major",
    subject: "Microservices architecture proposal",
    text: "I propose restructuring the application into microservices for better scalability and maintainability.",
    summary:
      "James proposes restructuring the application into microservices for better scalability.",
    tags: ["enhancement", "performance"],
    metadata: null,
    createdAt: daysAgo(50),
    updatedAt: daysAgo(50),
  },
  {
    id: "2q6s66qs-62ps-9500-310s-01q50813usq6",
    from: "laura.ux@example.com",
    impact: "minor",
    subject: "Onboarding flow improvements",
    text: "The user onboarding flow needs improvements to reduce drop-off rates. Many users abandon the process at step 3.",
    summary:
      "Laura suggests improvements to the user onboarding flow to reduce drop-off rates.",
    tags: ["ux", "enhancement"],
    metadata: null,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(60),
  },
  {
    id: "4r7t77rt-73qt-0611-421t-12r61924vtr7",
    from: "kevin.security@example.com",
    impact: "critical",
    subject: "XSS vulnerability found",
    text: "I discovered a cross-site scripting vulnerability in the comment section. User input is not being properly sanitized.",
    summary:
      "Kevin discovered a cross-site scripting vulnerability in the comment section.",
    tags: ["security", "bug"],
    metadata: null,
    createdAt: daysAgo(70),
    updatedAt: daysAgo(70),
  },
  {
    id: "6s8u88su-84ru-1722-532u-23s72035wus8",
    from: "emily.qa@example.com",
    impact: "major",
    subject: "Test coverage gaps",
    text: "We have several areas with insufficient test coverage, particularly in the payment processing module.",
    summary: "Emily identified several areas with insufficient test coverage.",
    tags: ["enhancement", "dx"],
    metadata: null,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(90),
  },
  {
    id: "8t9v99tv-95st-2833-643v-34t83146xvt9",
    from: "robert.user@example.com",
    impact: "minor",
    subject: "Export functionality request",
    text: "I would like to see more export options for data analysis, particularly CSV and Excel formats.",
    summary: "Robert would like to see more export options for data analysis.",
    tags: ["feature_request", "enhancement"],
    metadata: null,
    createdAt: daysAgo(100),
    updatedAt: daysAgo(100),
  },
  {
    id: "0u0w00uw-06tu-3944-754w-45u94257yuw0",
    from: "sophia.design@example.com",
    impact: "major",
    subject: "Design system inconsistencies",
    text: "I found several inconsistencies in the design system implementation. Colors and spacing don't match the documentation.",
    summary:
      "Sophia found several inconsistencies in the design system implementation.",
    tags: ["ui", "ux", "enhancement"],
    metadata: null,
    createdAt: daysAgo(120),
    updatedAt: daysAgo(120),
  },
  {
    id: "2v1x11vx-17uv-4055-865x-56v05368zvx1",
    from: "daniel.dev@example.com",
    impact: "critical",
    subject: "Memory leak in image processing",
    text: "There's a memory leak when processing large images. Memory usage keeps increasing until the app crashes.",
    summary: "Daniel discovered a memory leak when processing large images.",
    tags: ["bug", "performance"],
    metadata: null,
    createdAt: daysAgo(135),
    updatedAt: daysAgo(135),
  },
  {
    id: "4w2y22wy-28vw-5166-976y-67w16479axy2",
    from: "olivia.support@example.com",
    impact: "major",
    subject: "Documentation improvements needed",
    text: "The API documentation needs more examples and better explanations of error responses.",
    summary:
      "Olivia suggests improving the API documentation with more examples.",
    tags: ["api", "enhancement"],
    metadata: null,
    createdAt: daysAgo(150),
    updatedAt: daysAgo(150),
  },
  {
    id: "6x3z33xz-39wx-6277-087z-78x27580byz3",
    from: "michael.legal@example.com",
    impact: "minor",
    subject: "Terms of service update",
    text: "We need to update the terms of service to reflect our new features and data handling practices.",
    summary:
      "Michael requests updates to the terms of service for new features.",
    tags: ["legal", "enhancement"],
    metadata: null,
    createdAt: daysAgo(160),
    updatedAt: daysAgo(160),
  },
  {
    id: "8y4a44ya-40xy-7388-198a-89y38691cza4",
    from: "isabella.dev@example.com",
    impact: "critical",
    subject: "Database migration failure",
    text: "The database migration is failing for some users, causing data loss and application errors.",
    summary:
      "Isabella reports that the database migration is failing for some users.",
    tags: ["bug", "performance"],
    metadata: null,
    createdAt: daysAgo(180),
    updatedAt: daysAgo(180),
  },
  {
    id: "0z5b55zb-51yz-8499-209b-90z49702dab5",
    from: "william.architect@example.com",
    impact: "major",
    subject: "Caching strategy proposal",
    text: "I propose implementing a new caching strategy to improve performance and reduce database load.",
    summary:
      "William proposes implementing a new caching strategy for better performance.",
    tags: ["enhancement", "performance"],
    metadata: null,
    createdAt: daysAgo(200),
    updatedAt: daysAgo(200),
  },
  {
    id: "2a6c66ac-62za-9500-310c-01a50813ebc6",
    from: "ava.ux@example.com",
    impact: "minor",
    subject: "User feedback collection",
    text: "We should add a feedback collection widget to gather user insights and improve the product.",
    summary:
      "Ava suggests adding a feedback collection widget to gather user insights.",
    tags: ["ux", "enhancement"],
    metadata: null,
    createdAt: daysAgo(210),
    updatedAt: daysAgo(210),
  },
  {
    id: "4b7d77bd-73ab-0611-421d-12b61924fcd7",
    from: "ethan.security@example.com",
    impact: "critical",
    subject: "Authentication bypass found",
    text: "I discovered a potential authentication bypass in the admin panel. Unauthorized users can access protected routes.",
    summary:
      "Ethan discovered a potential authentication bypass in the admin panel.",
    tags: ["security", "bug"],
    metadata: null,
    createdAt: daysAgo(225),
    updatedAt: daysAgo(225),
  },
  {
    id: "6c8e88ce-84bc-1722-532e-23c72035gde8",
    from: "mia.qa@example.com",
    impact: "major",
    subject: "Automated testing improvements",
    text: "We need to implement more automated end-to-end tests to catch regressions early.",
    summary: "Mia suggests implementing more automated end-to-end tests.",
    tags: ["enhancement", "dx"],
    metadata: null,
    createdAt: daysAgo(240),
    updatedAt: daysAgo(240),
  },
  {
    id: "8d9f99df-95cd-2833-643f-34d83146hef9",
    from: "noah.user@example.com",
    impact: "minor",
    subject: "Bulk operations request",
    text: "I would like to see bulk operation capabilities for common tasks like deleting multiple items at once.",
    summary:
      "Noah would like to see bulk operation capabilities for common tasks.",
    tags: ["feature_request", "enhancement"],
    metadata: null,
    createdAt: daysAgo(260),
    updatedAt: daysAgo(260),
  },
  {
    id: "0e0g00eg-06de-3944-754g-45e94257ifg0",
    from: "amelia.design@example.com",
    impact: "major",
    subject: "Color contrast issues",
    text: "There are several color contrast issues affecting accessibility. Some text is hard to read against its background.",
    summary:
      "Amelia found several color contrast issues affecting accessibility.",
    tags: ["ui", "ux", "enhancement"],
    metadata: null,
    createdAt: daysAgo(300),
    updatedAt: daysAgo(300),
  },
];
